/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;
import java.awt.Color;
import javax.swing.JOptionPane;
import model.btnGrid;

/**
 *
 * @author jushuu
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
   Methods methods= new Methods();
    
    public view() {
        
        initComponents();
        //PaintDefault colors
        methods.fillZones(jpCamelot,jpAvalon,jpShambhala);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpAvalon = new javax.swing.JPanel();
        jpShambhala = new javax.swing.JPanel();
        jpCamelot = new javax.swing.JPanel();
        btnReservar = new javax.swing.JButton();
        sldPercent = new javax.swing.JSlider();
        cmbCategory = new javax.swing.JComboBox<>();
        cmbNumChairs = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1620, 920));
        setSize(new java.awt.Dimension(1620, 920));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpAvalon.setOpaque(false);

        javax.swing.GroupLayout jpAvalonLayout = new javax.swing.GroupLayout(jpAvalon);
        jpAvalon.setLayout(jpAvalonLayout);
        jpAvalonLayout.setHorizontalGroup(
            jpAvalonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jpAvalonLayout.setVerticalGroup(
            jpAvalonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        getContentPane().add(jpAvalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 840, 170));

        jpShambhala.setOpaque(false);

        javax.swing.GroupLayout jpShambhalaLayout = new javax.swing.GroupLayout(jpShambhala);
        jpShambhala.setLayout(jpShambhalaLayout);
        jpShambhalaLayout.setHorizontalGroup(
            jpShambhalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jpShambhalaLayout.setVerticalGroup(
            jpShambhalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        getContentPane().add(jpShambhala, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 690, 840, 170));

        jpCamelot.setOpaque(false);

        javax.swing.GroupLayout jpCamelotLayout = new javax.swing.GroupLayout(jpCamelot);
        jpCamelot.setLayout(jpCamelotLayout);
        jpCamelotLayout.setHorizontalGroup(
            jpCamelotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jpCamelotLayout.setVerticalGroup(
            jpCamelotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );

        getContentPane().add(jpCamelot, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 840, 180));

        btnReservar.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        btnReservar.setText("Reservar");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });
        getContentPane().add(btnReservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 800, 170, 50));

        sldPercent.setBackground(new java.awt.Color(4, 2, 2));
        sldPercent.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        sldPercent.setMajorTickSpacing(5);
        sldPercent.setMaximum(80);
        sldPercent.setPaintLabels(true);
        sldPercent.setPaintTicks(true);
        sldPercent.setPaintTrack(false);
        sldPercent.setToolTipText("");
        sldPercent.setValue(0);
        getContentPane().add(sldPercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 700, 520, 70));

        cmbCategory.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Camelot", "Avalon", "Shambhala" }));
        getContentPane().add(cmbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 390, 170, -1));

        cmbNumChairs.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        cmbNumChairs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        getContentPane().add(cmbNumChairs, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 490, 80, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/Camelot.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 890));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        // TODO add your handling code here:
        methods.resetColors();
        if(sldPercent.getValue()>=80||80-sldPercent.getValue()<Integer.parseInt((String)cmbNumChairs.getSelectedItem())){
            JOptionPane.showMessageDialog(rootPane,"No hay suficientes espacios libres para comprar");
        }else{
                //Get and send the value of chair that was reserved
            methods.fillBoughtChairs(sldPercent.getValue());
            //Search the new chairs that was bought
            methods.buyTickets(Integer.parseInt((String)cmbNumChairs.getSelectedItem()),(String)cmbCategory.getSelectedItem(),sldPercent.getValue());
        }
        
    }//GEN-LAST:event_btnReservarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReservar;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbNumChairs;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jpAvalon;
    private javax.swing.JPanel jpCamelot;
    private javax.swing.JPanel jpShambhala;
    private javax.swing.JSlider sldPercent;
    // End of variables declaration//GEN-END:variables
}
