/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class controller_Main */

#ifndef _Included_controller_Main
#define _Included_controller_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     controller_Main
 * Method:    nativeGreeting
 * Signature: (ILjava/lang/String;I)[I
 */
JNIEXPORT jintArray JNICALL Java_controller_Main_nativeGreeting
  (JNIEnv *, jobject, jint, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
